
codecov:
  notify:
    wait_for_ci: false

github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
