# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter
$schema: https://raw.githubusercontent.com/release-drafter/release-drafter/refs/tags/v7.7.0/schema.json

name-template: "Release $RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"
category-template: "### $TITLE"

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ":boom: Breaking changes"
    semver-increment: major
    labels:
      - breaking
  - title: ":fire: Removed"
    labels:
      - removed
  - title: ":rewind: Reverted Changes"
    labels:
      - revert
      - reverted
  - title: ":wastebasket: Deprecated"
    labels:
      - deprecated
  - title: ":tada: New features and improvements"
    exclusive: true
    semver-increment: minor
    labels:
      - enhancement
      - feature
  - title: ":bug: Bug Fixes"
    exclusive: true
    semver-increment: patch
    labels:
      - bug
      - bugfix
      - regression
  - title: ":white_check_mark: Tests"
    exclusive: true
    labels:
      - tests
  - title: ":gear: Code or Repo Maintenance"
    exclusive: true
    labels:
      - chore
      - cleanup
  - title: ":memo: Documentation updates"
    exclusive: true
    labels:
      - documentation
  - title: ":arrow_up: Dependency updates"
    exclusive: true
    collapse-after: 3
    labels:
      - dependencies # Default label used by Dependabot
  - title: ":construction_worker: CI & build changes"
    labels:
      - ci
      - build

exclude-labels:
  - skip-changelog
  - invalid

autolabeler:
  - label: ci
    files:
      - ".github/workflows/*"
      - ".github/dependabot.yml"
    branch:
      - '/ci\/.+/'
      - "/ci-.+/"
  - label: documentation
    files:
      - "*.md"
    branch:
      - '/docs?\/.+/'
      - "/docs?-.+/"
  - label: bug
    branch:
      - '/fix\/.+/'
      - "/fix-.+/"
  - label: chore
    branch:
      - '/chore\/.+/'
      - "/chore-.+/"
  - label: feature
    branch:
      - '/feature\/.+/'
      - "/feature-.+/"
      - '/feat\/.+/'
      - "/feat-.+/"
  - label: skip-changelog
    branch:
      - "/release-.*/"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

template: |
  ## :sparkles: What's New

  $CHANGES
