_extends:
  from: jellyfin/jellyfin-meta-plugins
  strategy:
    categories: append

name-template: "Release $RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"

categories:
  - type: version-resolver
    semver-increment: major
    when:
      labels: [major]
  - type: version-resolver
    semver-increment: minor
    when:
      labels: [minor]
  - type: version-resolver
    semver-increment: patch
    when:
      labels: [patch]
  - type: version-resolver
    semver-increment: patch

template: |
  ## :sparkles: What's New

  $CHANGES
