parameters:
  python_versions : []

steps:
  - ${{ each py_version in parameters.py_versions }}:
    - task: usePythonVersion@0
      inputs:
        versionSpec: '3.6'

    - checkout: self
      clean: true

    - script: python3 -m pip install --user -r jellyfin-kodi/requirements-dev.txt
      displayName: 'Install dev dependencies'

    - script: python3 jellyfin-kodi/build.py --${{ py_version }} --source=jellyfin-kodi --output=$(Build.ArtifactStagingDirectory)/plugin.video.jellyfin-${{ py_version }}.zip
      displayName: 'Build ${{ py_version }} addon zip'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish ${{ py_version }} artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/plugin.video.jellyfin-${{ py_version }}.zip'
        artifactName: 'plugin.video.jellyfin-${{ py_version }}-$(Build.BuildNumber)'

