name: Auto Label

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  auto_label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Runs Autolabeler.
      - uses: release-drafter/release-drafter/autolabeler@v7.7.0
