name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5.17.5
        env:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
